bash ./splittingScripts10/CuttingScript_01.sh &
bash ./splittingScripts10/CuttingScript_02.sh &
bash ./splittingScripts10/CuttingScript_03.sh &
bash ./splittingScripts10/CuttingScript_04.sh &
bash ./splittingScripts10/CuttingScript_05.sh &
bash ./splittingScripts10/CuttingScript_06.sh &
bash ./splittingScripts10/CuttingScript_07.sh &
bash ./splittingScripts10/CuttingScript_08.sh &
bash ./splittingScripts10/CuttingScript_09.sh &
bash ./splittingScripts10/CuttingScript_10.sh &
